"""A frozen snapshot of the llm-d-benchmark catalog (specs / harnesses / workloads).

WHY THIS EXISTS
---------------
Flow validation must run **hermetically** in CI, where ``llm-d-benchmark`` and ``llm-d``
are empty gitlinks. But the things we want to validate consult the *live on-disk catalog*:

  * the command policy's ``ref_catalog`` checks (``--spec``/``-l``/``-w`` must name a
    real spec/harness/workload), and
  * the ``SessionPlan`` validator (``validate_plan``).

With no repo present those lists are empty and *every* spec/harness/workload would fail to
validate — so the harness could not exercise the real policy. Seeding a ``ToolContext``
with this snapshot lets the harness validate the agent's commands against the **real**
policy exactly as it would in production, with zero repos on disk.

This is a *snapshot*, not a source of truth. ``test_flows.py::test_snapshot_matches_live``
asserts that every name the flows reference still exists in the **live** catalog whenever
the repo IS present (local dev / a CI job that checks out the submodules), so drift between
this snapshot and the upstream repo is caught loudly.

Generated from ``app.tools.setup.catalog.build_catalog`` against llm-d-benchmark @ a75d91e (2026-10-06).
Regenerate with:  ``make snapshot-catalog``  (see the Makefile).
"""
from __future__ import annotations

from typing import Any

# ---- the snapshot (shape mirrors build_catalog's return) ---------------------

SPECS: list[str] = ['cicd/cks',
 'cicd/gke',
 'cicd/kind',
 'cicd/ocp',
 'cicd/ocp-keda',
 'cicd/ocp-keda-fma-hotstart',
 'cicd/ocp-keda-fma-warmstart',
 'examples/cpu',
 'examples/eval-containers-aider-polyglot',
 'examples/eval-containers-aider-polyglot-gpu',
 'examples/eval-containers-gaia',
 'examples/eval-containers-gaia-gpu',
 'examples/fma',
 'examples/gpu',
 'examples/launcher',
 'examples/multi-model-optimized-baseline',
 'examples/sim',
 'examples/spyre',
 'examples/spyre-s390x',
 'experimental/kimi-k3-h100',
 'guides/agentic-serving',
 'guides/epp-keda-saturation',
 'guides/fast-model-actuation-base',
 'guides/fast-model-actuation-keda',
 'guides/flow-control',
 'guides/keda-epp-token-aware',
 'guides/keda-epp-token-aware-pd-disaggregation',
 'guides/multimodal-serving-aggregation',
 'guides/multimodal-serving-e-disaggregation',
 'guides/nok8s',
 'guides/optimized-baseline',
 'guides/p2p-kv-cache-sharing',
 'guides/pd-disaggregation',
 'guides/precise-prefix-cache-routing',
 'guides/predicted-latency-routing',
 'guides/tiered-prefix-cache',
 'guides/turn-priority-fairness',
 'guides/wide-ep',
 'guides/workload-autoscaling']

HARNESSES: list[str] = ['aiperf',
 'eval-containers',
 'guidellm',
 'inference-perf',
 'inferencemax',
 'lm-eval',
 'nop',
 'priority-mix',
 'vllm-benchmark']

WORKLOADS: list[str] = ['accuracy_default.yaml',
 'agent_llm_traces_v2.yaml',
 'agentic_code_generation.yaml',
 'aider-polyglot.yaml',
 'approx_prefix_cache_ladder.yaml',
 'approx_prefix_cache_smoke.yaml',
 'approx_prefix_cache_zero_reuse_control.yaml',
 'chatbot_sharegpt.yaml',
 'chatbot_synthetic.yaml',
 'code_completion_synthetic.yaml',
 'concurrent-1k-1k.yaml',
 'concurrent-heavy-heterogeneous.yaml',
 'dataset.yaml',
 'fixed_dataset.yaml',
 'gaia.yaml',
 'guide_async-multitenant_1.yaml',
 'guide_async-multitenant_2.yaml',
 'guide_kimi-k3-h100_1.yaml',
 'guide_multimodal-serving_1.yaml',
 'guide_optimized-baseline_1.yaml',
 'guide_optimized-baseline_2.yaml',
 'guide_p2p-kv-cache-sharing_1.yaml',
 'guide_pd-disaggregation_1.yaml',
 'guide_pd-disaggregation_2.yaml',
 'guide_precise-prefix-cache-routing_1.yaml',
 'guide_precise-prefix-cache-routing_2.yaml',
 'guide_predicted-latency-routing_1.yaml',
 'guide_tiered-prefix-cache_1.yaml',
 'guide_wide-ep_1.yaml',
 'interactive-chat.yaml',
 'multi-turn.yaml',
 'nop.yaml',
 'otel_traces.yaml',
 'priority_mix.yaml',
 'random_concurrent.yaml',
 'random_decode_heavy.yaml',
 'random_prefill_heavy.yaml',
 'random_symmetrical.yaml',
 'sanity.yaml',
 'sanity_concurrent.yaml',
 'sanity_random.yaml',
 'shared_prefix_multi_turn_chat.yaml',
 'shared_prefix_synthetic.yaml',
 'shared_prefix_synthetic_heavy.yaml',
 'shared_prefix_synthetic_short.yaml',
 'sharegpt.yaml',
 'sonnet_concurrent.yaml',
 'summarization_synthetic.yaml',
 'synthetic.yaml',
 'weka_traces.yaml']

WORKLOADS_BY_HARNESS: dict[str, list[str]] = {'aiperf': ['dataset.yaml', 'sanity_random.yaml', 'synthetic.yaml'],
 'eval-containers': ['aider-polyglot.yaml', 'gaia.yaml'],
 'guidellm': ['concurrent-1k-1k.yaml',
              'concurrent-heavy-heterogeneous.yaml',
              'multi-turn.yaml',
              'sanity_concurrent.yaml',
              'sanity_random.yaml',
              'summarization_synthetic.yaml'],
 'inference-perf': ['agent_llm_traces_v2.yaml',
                    'agentic_code_generation.yaml',
                    'approx_prefix_cache_ladder.yaml',
                    'approx_prefix_cache_smoke.yaml',
                    'approx_prefix_cache_zero_reuse_control.yaml',
                    'chatbot_sharegpt.yaml',
                    'chatbot_synthetic.yaml',
                    'code_completion_synthetic.yaml',
                    'guide_async-multitenant_1.yaml',
                    'guide_async-multitenant_2.yaml',
                    'guide_kimi-k3-h100_1.yaml',
                    'guide_multimodal-serving_1.yaml',
                    'guide_optimized-baseline_1.yaml',
                    'guide_optimized-baseline_2.yaml',
                    'guide_p2p-kv-cache-sharing_1.yaml',
                    'guide_pd-disaggregation_1.yaml',
                    'guide_pd-disaggregation_2.yaml',
                    'guide_precise-prefix-cache-routing_1.yaml',
                    'guide_precise-prefix-cache-routing_2.yaml',
                    'guide_predicted-latency-routing_1.yaml',
                    'guide_tiered-prefix-cache_1.yaml',
                    'guide_wide-ep_1.yaml',
                    'interactive-chat.yaml',
                    'otel_traces.yaml',
                    'random_concurrent.yaml',
                    'random_decode_heavy.yaml',
                    'random_prefill_heavy.yaml',
                    'random_symmetrical.yaml',
                    'sanity_random.yaml',
                    'shared_prefix_multi_turn_chat.yaml',
                    'shared_prefix_synthetic.yaml',
                    'shared_prefix_synthetic_heavy.yaml',
                    'shared_prefix_synthetic_short.yaml',
                    'summarization_synthetic.yaml',
                    'weka_traces.yaml'],
 'inferencemax': ['random_concurrent.yaml', 'sanity_random.yaml'],
 'lm-eval': ['accuracy_default.yaml', 'sanity.yaml'],
 'nop': ['nop.yaml'],
 'priority-mix': ['priority_mix.yaml', 'sanity.yaml'],
 'vllm-benchmark': ['fixed_dataset.yaml',
                    'guide_wide-ep_1.yaml',
                    'random_concurrent.yaml',
                    'sanity_random.yaml',
                    'sharegpt.yaml',
                    'sonnet_concurrent.yaml']}

# Scenario identifiers captured independently from the live catalog.
SCENARIOS: list[str] = ['cicd/cks',
 'cicd/gke',
 'cicd/kind',
 'cicd/ocp',
 'cicd/ocp-keda',
 'cicd/ocp-keda-fma-hotstart',
 'cicd/ocp-keda-fma-warmstart',
 'examples/cpu',
 'examples/eval-containers-aider-polyglot',
 'examples/eval-containers-aider-polyglot-gpu',
 'examples/eval-containers-gaia',
 'examples/eval-containers-gaia-gpu',
 'examples/fma',
 'examples/gpu',
 'examples/launcher',
 'examples/multi-model-optimized-baseline',
 'examples/sim',
 'examples/spyre',
 'examples/spyre-s390x',
 'experimental/kimi-k3-h100',
 'guides/agentic-serving',
 'guides/epp-keda-saturation',
 'guides/fast-model-actuation-base',
 'guides/fast-model-actuation-keda',
 'guides/flow-control',
 'guides/keda-epp-token-aware',
 'guides/keda-epp-token-aware-pd-disaggregation',
 'guides/multimodal-serving-aggregation',
 'guides/multimodal-serving-e-disaggregation',
 'guides/nok8s',
 'guides/optimized-baseline',
 'guides/p2p-kv-cache-sharing',
 'guides/pd-disaggregation',
 'guides/precise-prefix-cache-routing',
 'guides/predicted-latency-routing',
 'guides/tiered-prefix-cache',
 'guides/turn-priority-fairness',
 'guides/wide-ep',
 'guides/workload-autoscaling']


def frozen_catalog() -> dict[str, Any]:
    """A catalog dict shaped exactly like ``app.tools.setup.catalog.build_catalog`` returns,
    so it can be dropped straight into ``ToolContext._catalog``."""
    return {
        "present": True,
        "repo_path": "<frozen-snapshot>",
        "specs": list(SPECS),
        "harnesses": list(HARNESSES),
        "workloads": list(WORKLOADS),
        "workloads_by_harness": {k: list(v) for k, v in WORKLOADS_BY_HARNESS.items()},
        "scenarios": list(SCENARIOS),
    }
