#!/usr/bin/env bash
# SessionEnd hook — keep ./context and memory fresh. Two parts:
#   (1) MECHANICAL: regenerate context/README.md, an auto index of the context files the agent has
#       accumulated (tool-failure lessons, scratch findings it reuses across sessions).
#   (2) NUDGE: a hook can maintain the index but cannot author good content — so it reminds you to
#       fold durable findings into memory + ./context while the session is fresh.
# Sole SessionEnd nudge (the separate reflect_session_end.sh was removed — its memory-reflection
# reminder is folded into the nudge below). Disable: CONTEXT_SYNC_OFF=1.
set -u
[ "${CONTEXT_SYNC_OFF:-0}" = "1" ] && exit 0
CTX="${CLAUDE_PROJECT_DIR:-$PWD}/context"
[ -d "$CTX" ] || exit 0
CTX="$CTX" python3 - <<'PY' 2>/dev/null || true
import os, time, glob
ctx = os.environ["CTX"]
lines = ["# ./context — auto-maintained index",
         "",
         "Living context the agent accumulates across sessions (tool-failure lessons, reusable",
         "scratch findings). This index is regenerated by `context_sync.sh` on SessionEnd — edit",
         "the files themselves, not this list.",
         "",
         "_last synced: %s_" % time.strftime("%Y-%m-%d %H:%M:%SZ", time.gmtime()),
         ""]
files = []
for p in sorted(glob.glob(os.path.join(ctx, "**", "*"), recursive=True)):
    b = os.path.basename(p)
    if os.path.isfile(p) and b != "README.md" and not b.startswith("."):
        rel = os.path.relpath(p, ctx)
        try:
            n = sum(1 for _ in open(p, encoding="utf-8", errors="replace"))
        except Exception:
            n = 0
        mt = time.strftime("%Y-%m-%d", time.gmtime(os.path.getmtime(p)))
        files.append("- `%s` — %d lines (updated %s)" % (rel, n, mt))
lines += files if files else ["_(no context files yet)_"]
open(os.path.join(ctx, "README.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
PY
cat >&2 <<'NUDGE'

──────── context & memory sync ────────
Fold anything durable from this session into the right place while it's fresh:
  • reusable facts / preferences / project state -> a memory file (+ a line in MEMORY.md)
  • tool-failure lessons, scratch findings the agent reuses -> ./context/ files
The ./context index (context/README.md) was just regenerated.
────────────────────────────────────────
NUDGE
exit 0
